name: Terraform CI/CD Pipeline with Manual Approval

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from the repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6  # Adjust to your required version

      # Set up AWS credentials
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Modify to your region if needed

      # Terraform Initialization
      - name: Terraform Init
        run: terraform init

      # Terraform Validate (check for syntax issues)
      - name: Terraform Validate
        run: terraform validate

      # Run Terraform Plan (this will display the changes to be applied)
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        env:
         TF_VAR_github_token: ${{ secrets.GH_TOKEN }}

      # Save the Terraform Plan output as an artifact
      - name: Save Terraform Plan output
        run: terraform plan -out=tfplan > terraform_plan.txt
        continue-on-error: true  # Allow this step to run even if plan fails

  # Manual approval step before apply
  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-plan  # This ensures terraform-apply only runs after terraform-plan

    steps:
      # Checkout the code from the repo
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Terraform again in the apply step
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      # Set up AWS credentials again
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Modify to your region if needed

      # Terraform Initialization
      - name: Terraform Init
        run: terraform init

      # Wait for manual approval before applying changes
      - name: Request manual approval
        run: echo "Waiting for manual approval to apply changes..."

      # Manual approval step (this will pause until approved in GitHub UI)
      - name: Manual Approval
        uses: peter-evans/manual-approval@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}

      # Terraform Apply after approval
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
         TF_VAR_github_token: ${{ secrets.GH_TOKEN }}
